remote_theme: academicpages/academicpages.github.io

locale: "en-US"
title: "David Herszenhaut"
title_separator: "-"
name: &name "David Herszenhaut"
description: &description "My personal website!"
url: https://davidherszenhaut.github.io
baseurl: ""
repository: "davidherszenhaut/davidherszenhaut.github.io"

author:
  avatar: "profile.jpg"
  name: "David Herszenhaut"
  pronouns: "he/him"
  bio: "I like making stuff sometimes."
  location: "Atlanta, Georgia"
  employer: "Automated Logic"
  email: "davidherszenhaut.business@gmail.com"

  github: "davidherszenhaut"
  linkedin: "davidherszenhaut"
  youtube: "OvertakeMusicChannel"

breadcrumbs: true
atom_feed:
  hide: false
  path: 

include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
increments: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_codray: false

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
