remote_theme: academicpages/academicpages.github.io

locale: "en-US"
title: "David Herszenhaut"
title_separator: "-"
name: &name "David Herszenhaut"
description: &description "My personal website!"
url: https://davidherszenhaut.github.io
baseurl: ""
repository: "davidherszenhaut/davidherszenhaut.github.io"

author:
  avatar: "profile.jpg"
  name: "David Herszenhaut"
  pronouns: "he/him"
  bio: "I like making stuff sometimes."
  location: "Atlanta, Georgia"
  employer: "Automated Logic"
  email: "davidherszenhaut.business@gmail.com"

  github: "davidherszenhaut"
  linkedin: "davidherszenhaut"
  youtube: "OvertakeMusicChannel"
  bandcamp: "https://overtakemusicchannel.bandcamp.com/"

breadcrumbs: false
future: false
atom_feed:
  hide: false
  path: 

include:
  - .htaccess
  - _pages
  - files
exclude:
  - .github
  - LICENSE
  - README
keep_files:
  - .git
encoding: "utf-8"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/

plugins:
  - jekyll-feed
whitelist:
  - jekyll-feed

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
